### Basic Code

In [1]:
import numpy as np

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def possible(row, column, number):
    global grid
    #Is the number appearing in the given row?
    for i in range(0,9):
        if grid[row][i] == number:
            return False

    #Is the number appearing in the given column?
    for i in range(0,9):
        if grid[i][column] == number:
            return False
    
    #Is the number appearing in the given square?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == number:
                return False

    return True

def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve()
                        grid[row][column] = 0

                return
      
    print(np.matrix(grid))
    input('More possible solutions')

solve()







    
            



[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
More possible solutions
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


KeyboardInterrupt: Interrupted by user

### Try 1

In [2]:
import numpy as np

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def possible(row, column, number):
    global grid
    # Is the number appearing in the given row?
    for i in range(0, 9):
        if grid[row][i] == number:
            return False

    # Is the number appearing in the given column?
    for i in range(0, 9):
        if grid[i][column] == number:
            return False

    # Is the number appearing in the given square?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == number:
                return False

    return True

def solve():
    global grid
    for row in range(0, 9):
        for column in range(0, 9):
            if grid[row][column] == 0:
                for number in range(1, 10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve()
                        grid[row][column] = 0

                return

    print(np.matrix(grid))
    choice = input('More possible solutions? (y/n): ')
    if choice.lower() == 'y':
        solve()

solve()


[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
More possible solutions? (y/n): y
[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
More possible solutions? (y/n): n
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More possible solutions? (y/n): y
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More possible solutions? (y/n): 


### Try 2

In [4]:
import cv2
import numpy as np

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def draw_grid():
    img = np.zeros((450, 450, 3), np.uint8)
    cell_size = 50

    for i in range(0, 10):
        if i % 3 == 0:
            thickness = 2
        else:
            thickness = 1

        cv2.line(img, (0, i * cell_size), (450, i * cell_size), (255, 255, 255), thickness)
        cv2.line(img, (i * cell_size, 0), (i * cell_size, 450), (255, 255, 255), thickness)

    for i in range(0, 9):
        for j in range(0, 9):
            if grid[i][j] != 0:
                text = str(grid[i][j])
                text_size = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 1, 2)[0]
                text_x = int((cell_size - text_size[0]) / 2 + j * cell_size)
                text_y = int((cell_size + text_size[1]) / 2 + i * cell_size)
                cv2.putText(img, text, (text_x, text_y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

    return img

def possible(row, column, number):
    global grid
    # Is the number appearing in the given row?
    for i in range(0, 9):
        if grid[row][i] == number:
            return False

    # Is the number appearing in the given column?
    for i in range(0, 9):
        if grid[i][column] == number:
            return False

    # Is the number appearing in the given square?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == number:
                return False

    return True

def solve(img):
    global grid

    for row in range(0, 9):
        for column in range(0, 9):
            if grid[row][column] == 0:
                for number in range(1, 10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve(img)
                        grid[row][column] = 0

                return

    cv2.imshow("Sudoku Solver", img)
    cv2.waitKey(0)

def main():
    img = draw_grid()
    solve(img)

    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()


### Try 3


In [1]:
import cv2
import numpy as np
import time

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def draw_grid():
    img = np.zeros((450, 450, 3), np.uint8)
    cell_size = 50

    for i in range(0, 10):
        if i % 3 == 0:
            thickness = 2
        else:
            thickness = 1

        cv2.line(img, (0, i * cell_size), (450, i * cell_size), (255, 255, 255), thickness)
        cv2.line(img, (i * cell_size, 0), (i * cell_size, 450), (255, 255, 255), thickness)

    for i in range(0, 9):
        for j in range(0, 9):
            if grid[i][j] != 0:
                text = str(grid[i][j])
                text_size = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 1, 2)[0]
                text_x = int((cell_size - text_size[0]) / 2 + j * cell_size)
                text_y = int((cell_size + text_size[1]) / 2 + i * cell_size)
                cv2.putText(img, text, (text_x, text_y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

    return img

def possible(row, column, number):
    global grid
    # Is the number appearing in the given row?
    for i in range(0, 9):
        if grid[row][i] == number:
            return False

    # Is the number appearing in the given column?
    for i in range(0, 9):
        if grid[i][column] == number:
            return False

    # Is the number appearing in the given square?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == number:
                return False

    return True

def solve(img):
    global grid

    for row in range(0, 9):
        for column in range(0, 9):
            if grid[row][column] == 0:
                for number in range(1, 10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        img = draw_grid()
                        cv2.imshow("Sudoku Solver", img)
                        cv2.waitKey(500)  # Delay of 0.5 seconds
                        solve(img)
                        grid[row][column] = 0
                        img = draw_grid()
                        cv2.imshow("Sudoku Solver", img)
                        cv2.waitKey(500)  # Delay of 0.5 seconds

                return

    cv2.imshow("Sudoku Solver", img)
    cv2.waitKey(0)

def main():
    img = draw_grid()
    cv2.imshow("Sudoku Solver", img)
    cv2.waitKey(500)  # Delay of 0.5 seconds
    solve(img)

    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()


KeyboardInterrupt: 

In [11]:
 cv2.destroyAllWindows()

### Try 4

In [ ]:
import cv2
import numpy as np
import time

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def draw_grid():
    img = np.zeros((450, 450, 3), np.uint8)
    cell_size = 50

    for i in range(0, 10):
        if i % 3 == 0:
            thickness = 2
        else:
            thickness = 1

        cv2.line(img, (0, i * cell_size), (450, i * cell_size), (255, 255, 255), thickness)
        cv2.line(img, (i * cell_size, 0), (i * cell_size, 450), (255, 255, 255), thickness)

    for i in range(0, 9):
        for j in range(0, 9):
            if grid[i][j] != 0:
                text = str(grid[i][j])
                text_size = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 1, 2)[0]
                text_x = int((cell_size - text_size[0]) / 2 + j * cell_size)
                text_y = int((cell_size + text_size[1]) / 2 + i * cell_size)
                cv2.putText(img, text, (text_x, text_y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

    return img

def possible(row, column, number):
    global grid
    # Is the number appearing in the given row?
    for i in range(0, 9):
        if grid[row][i] == number:
            return False

    # Is the number appearing in the given column?
    for i in range(0, 9):
        if grid[i][column] == number:
            return False

    # Is the number appearing in the given square?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == number:
                return False

    return True

def solve(img):
    global grid

    for row in range(0, 9):
        for column in range(0, 9):
            if grid[row][column] == 0:
                for number in range(1, 10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        img = draw_grid()
                        cv2.imshow("Sudoku Solver", img)
                        cv2.waitKey(1)  # Minimal delay
                        if cv2.waitKey(1) & 0xFF == ord('q'):  # Check if 'q' key is pressed
                            return
                        solve(img)
                        grid[row][column] = 0
                        img = draw_grid()
                        cv2.imshow("Sudoku Solver", img)
                        cv2.waitKey(1)  # Minimal delay

                return

    cv2.imshow("Sudoku Solver", img)
    cv2.waitKey(0)

def main():
    img = draw_grid()
    cv2.imshow("Sudoku Solver", img)
    cv2.waitKey(1)  # Minimal delay
    solve(img)

    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()


In [13]:
    cv2.destroyAllWindows()

### Try 5

In [14]:
import tkinter as tk

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def draw_grid():
    for i in range(9):
        for j in range(9):
            if grid[i][j] != 0:
                cell = tk.Label(root, text=grid[i][j], width=4, height=2, relief="solid", font=("Helvetica", 16))
                cell.grid(row=i, column=j)
            else:
                cell = tk.Entry(root, width=4, font=("Helvetica", 16))
                cell.grid(row=i, column=j)
                cell.insert(tk.END, "0")

def solve():
    global grid
    for row in range(9):
        for col in range(9):
            if grid[row][col] == 0:
                for num in range(1, 10):
                    if is_valid(row, col, num):
                        grid[row][col] = num
                        draw_grid()
                        root.update()
                        root.after(500)  # Delay of 0.5 seconds
                        solve()
                        grid[row][col] = 0
                        draw_grid()
                        root.update()
                        root.after(500)  # Delay of 0.5 seconds
                return

def is_valid(row, col, num):
    for i in range(9):
        if grid[row][i] == num or grid[i][col] == num:
            return False
    start_row = (row // 3) * 3
    start_col = (col // 3) * 3
    for i in range(3):
        for j in range(3):
            if grid[start_row + i][start_col + j] == num:
                return False
    return True

def solve_sudoku():
    for i in range(9):
        for j in range(9):
            if isinstance(grid[i][j], tk.Entry):
                grid[i][j] = int(grid[i][j].get())
    solve()

root = tk.Tk()
root.title("Sudoku Solver")

draw_grid()

solve_button = tk.Button(root, text="Solve", command=solve_sudoku)
solve_button.grid(row=9, columnspan=9)

root.mainloop()


Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Acer pc\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykernel_660\132595669.py", line 59, in solve_sudoku
    solve()
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykernel_660\132595669.py", line 35, in solve
    solve()
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykernel_660\132595669.py", line 35, in solve
    solve()
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykernel_660\132595669.py", line 35, in solve
    solve()
  [Previous line repeated 1 more time]
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykernel_660\132595669.py", line 32, in solve
    draw_grid()
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykernel_660\132595669.py", line 17, in draw_grid
    cell = tk.Label(root, text=grid[i][j], width=4, height=2, relief="solid", font=("Helvetica", 16))
  File "C:\Users\Acer pc\anaconda3\lib\tkinter\__init__.py", 

### Try 6

In [15]:
import tkinter as tk

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def draw_grid():
    for i in range(9):
        for j in range(9):
            if grid[i][j] != 0:
                cell = tk.Label(root, text=grid[i][j], width=4, height=2, relief="solid", font=("Helvetica", 16))
                cell.grid(row=i, column=j)
            else:
                cell = tk.Entry(root, width=4, font=("Helvetica", 16))
                cell.grid(row=i, column=j)
                cell.insert(tk.END, "0")

def solve():
    global grid
    for row in range(9):
        for col in range(9):
            if grid[row][col] == 0:
                for num in range(1, 10):
                    if is_valid(row, col, num):
                        grid[row][col] = num
                        draw_grid()
                        root.update()
                        root.after(10)  # Delay of 10 milliseconds
                        solve()
                        grid[row][col] = 0
                        draw_grid()
                        root.update()
                        root.after(10)  # Delay of 10 milliseconds
                return

def is_valid(row, col, num):
    for i in range(9):
        if grid[row][i] == num or grid[i][col] == num:
            return False
    start_row = (row // 3) * 3
    start_col = (col // 3) * 3
    for i in range(3):
        for j in range(3):
            if grid[start_row + i][start_col + j] == num:
                return False
    return True

def solve_sudoku():
    for i in range(9):
        for j in range(9):
            if isinstance(grid[i][j], tk.Entry):
                grid[i][j] = int(grid[i][j].get())
    solve()

root = tk.Tk()
root.title("Sudoku Solver")

draw_grid()

solve_button = tk.Button(root, text="Solve", command=solve_sudoku)
solve_button.grid(row=9, columnspan=9)

root.mainloop()


Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Acer pc\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Acer pc\anaconda3\lib\tkinter\__init__.py", line 2311, in destroy
    for c in list(self.children.values()): c.destroy()
  File "C:\Users\Acer pc\anaconda3\lib\tkinter\__init__.py", line 2580, in destroy
    self.tk.call('destroy', self._w)
KeyboardInterrupt
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Acer pc\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykernel_660\3597720835.py", line 59, in solve_sudoku
    solve()
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykernel_660\3597720835.py", line 35, in solve
    solve()
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykernel_660\3597720835.py", line 35, in solve
    solve()
  File "C:\Users\Acer pc\AppData\Local\Temp\ipykern

## Grid Generator 

In [23]:
import random

def generate_grid():
    grid = [[0] * 9 for _ in range(9)]
    fill_diagonal(grid)
    solve_grid(grid)
    remove_cells(grid)
    return grid

def fill_diagonal(grid):
    nums = list(range(1, 10))
    random.shuffle(nums)
    for i in range(0, 9, 3):
        fill_box(grid, i, i, nums)

def fill_box(grid, start_row, start_col, nums):
    num_index = 0
    for i in range(3):
        for j in range(3):
            grid[start_row + i][start_col + j] = nums[num_index]
            num_index = (num_index + 1) % 9

def solve_grid(grid):
    empty_cells = get_empty_cells(grid)
    solve_sudoku(grid, empty_cells)

def get_empty_cells(grid):
    empty_cells = []
    for row in range(9):
        for col in range(9):
            if grid[row][col] == 0:
                empty_cells.append((row, col))
    return empty_cells

def solve_sudoku(grid, empty_cells):
    if not empty_cells:
        return True

    row, col = empty_cells[0]
    nums = list(range(1, 10))
    random.shuffle(nums)

    for num in nums:
        if is_valid(grid, row, col, num):
            grid[row][col] = num
            if solve_sudoku(grid, empty_cells[1:]):
                return True
            grid[row][col] = 0

    return False

def is_valid(grid, row, col, num):
    return (
        is_valid_row(grid, row, num) and
        is_valid_column(grid, col, num) and
        is_valid_box(grid, row, col, num)
    )

def is_valid_row(grid, row, num):
    return num not in grid[row]

def is_valid_column(grid, col, num):
    return num not in [grid[row][col] for row in range(9)]

def is_valid_box(grid, row, col, num):
    start_row = (row // 3) * 3
    start_col = (col // 3) * 3
    for i in range(3):
        for j in range(3):
            if grid[start_row + i][start_col + j] == num:
                return False
    return True

def remove_cells(grid):
    num_cells_to_remove = random.randint(40, 50)
    cells = [(row, col) for row in range(9) for col in range(9)]
    random.shuffle(cells)
    for i in range(num_cells_to_remove):
        row, col = cells[i]
        grid[row][col] = 0

def print_grid(grid):
    for row in grid:
        print(row)

# Generate and print a Sudoku grid
grid = generate_grid()
print_grid(grid)


[0, 0, 0, 0, 8, 0, 0, 4, 2]
[0, 0, 4, 6, 0, 0, 0, 5, 0]
[0, 9, 0, 0, 0, 7, 0, 0, 3]
[0, 0, 0, 3, 0, 6, 0, 2, 0]
[0, 0, 3, 0, 7, 0, 0, 0, 1]
[0, 0, 2, 0, 0, 8, 0, 3, 7]
[7, 2, 0, 8, 4, 9, 0, 0, 0]
[0, 0, 0, 1, 0, 3, 2, 7, 0]
[0, 3, 0, 7, 6, 0, 0, 9, 8]


In [5]:
import cv2
import numpy as np
import time


def draw_grid():
    img = np.zeros((450, 450, 3), np.uint8)
    cell_size = 50

    for i in range(0, 10):
        if i % 3 == 0:
            thickness = 2
        else:
            thickness = 1

        cv2.line(img, (0, i * cell_size), (450, i * cell_size), (255, 255, 255), thickness)
        cv2.line(img, (i * cell_size, 0), (i * cell_size, 450), (255, 255, 255), thickness)

    for i in range(0, 9):
        for j in range(0, 9):
            if grid[i][j] != 0:
                text = str(grid[i][j])
                text_size = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 1, 2)[0]
                text_x = int((cell_size - text_size[0]) / 2 + j * cell_size)
                text_y = int((cell_size + text_size[1]) / 2 + i * cell_size)
                cv2.putText(img, text, (text_x, text_y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

    return img

def possible(row, column, number):
    global grid
    # Is the number appearing in the given row?
    for i in range(0, 9):
        if grid[row][i] == number:
            return False

    # Is the number appearing in the given column?
    for i in range(0, 9):
        if grid[i][column] == number:
            return False

    # Is the number appearing in the given square?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == number:
                return False

    return True

def solve(img):
    global grid

    for row in range(0, 9):
        for column in range(0, 9):
            if grid[row][column] == 0:
                for number in range(1, 10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        img = draw_grid()
                        cv2.imshow("Sudoku Solver", img)
                        cv2.waitKey(1)  # Minimal delay
                        if cv2.waitKey(1) & 0xFF == ord('q'):  # Check if 'q' key is pressed
                            return
                        solve(img)
                        grid[row][column] = 0
                        img = draw_grid()
                        cv2.imshow("Sudoku Solver", img)
                        cv2.waitKey(1)  # Minimal delay

                return

    cv2.imshow("Sudoku Solver", img)
    cv2.waitKey(0)

def main():
    img = draw_grid()
    cv2.imshow("Sudoku Solver", img)
    cv2.waitKey(1)  # Minimal delay
    solve(img)

    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()


KeyboardInterrupt: 